[profile.release]
lto = true
opt-level = 'z'

[workspace]
members = [
    "fp-provider",
    "protocol",
    "providers/prometheus",
    "providers/proxy",
    "runtimes/fp-provider-runtime",
]

# [patch."ssh://git@github.com/fiberplane/fp-bindgen.git"]
# fp-bindgen = { path = "../fp-bindgen/fp-bindgen" }
