[workspace]
members = ["fiberplane-pdk", "fiberplane-pdk-macros", "providers/*"]
exclude = ["providers/.cargo"]

[workspace.package]
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2021"
rust-version = "1.65"
version = "1.0.0-alpha.3"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
fp-bindgen = { version = "3.0.0-alpha.1" }
fp-bindgen-support = { version = "3.0.0-alpha.1" }
#fiberplane-models = { version = "1.0.0-alpha.2", registry = "artifactory" }
fiberplane-models = { git = "ssh://git@github.com/fiberplane/fiberplane-rs.git", branch = "main" }
fiberplane-pdk = { version = "1.0.0-alpha.3", path = "fiberplane-pdk" }
fiberplane-pdk-macros = { version = "1.0.0-alpha.3", path = "fiberplane-pdk-macros" }
#fiberplane-provider-bindings = { version = "1.0.0-alpha.2", registry = "artifactory" }
fiberplane-provider-bindings = { git = "ssh://git@github.com/fiberplane/fiberplane-rs.git", branch = "main" }

rmpv = { version = "1", features = ["with-serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3.15", features = [
  "macros",
  "serde-human-readable",
  "serde-well-known",
] }
tracing = "0.1.36"
url = { version = "2.2.2", features = ["serde"] }
vergen = { version = "7.4.2", default-features = false, features = [
  "build",
  "git",
] }

[patch.artifactory]
#fiberplane-models = { path = "../fiberplane-rs/fiberplane-models" }
#fiberplane-provider-bindings = { path = "../fiberplane-rs/fiberplane-provider-protocol/fiberplane-provider-bindings" }

[patch.crates-io]
#fp-bindgen = { path = "../fp-bindgen/fp-bindgen"}
#fp-bindgen-support = { path = "../fp-bindgen/fp-bindgen-support"}
#fp-bindgen = { git = "ssh://git@github.com/fiberplane/fp-bindgen.git", branch = "main" }
#fp-bindgen-support = { git = "ssh://git@github.com/fiberplane/fp-bindgen.git", branch = "main" }
