[package]
name = "fp-provider"
version = "1.0.0-alpha.1"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[dependencies]
once_cell = "1"
rmp-serde = "=1.0.0-beta.2"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
