[package]
name = "xtask"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
console = "0.15"
duct = "0.13"
thiserror = "1"
wasm-opt = "0.111"
