[package]
name = "provider-protocol"
version = "0.1.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[dependencies]
fp-bindgen = { version = "2", features = ["generators"] }
rmpv = "1.0.0"
serde_bytes = "0.11"
