[package]
name = "loki-provider"
description = "Fiberplane Loki Provider"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
fiberplane-pdk = { workspace = true }
serde = { workspace = true }
url = { workspace = true }

[build-dependencies]
vergen = { workspace = true }
