name: Build

on:
  push:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: "https://fiberplanebot:${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/"

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Check format
        # Skip formatting on main, since it's not critical and should've already
        # been checked before merging
        if: ${{ github.ref != 'refs/heads/main' }}
        run: cargo fmt -- --check

      - name: Lint code
        # Skip linting on main, since it's not critical and should've already
        # been checked before merging
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --workspace

      - name: Run tests
        run: cargo test --verbose

      - name: Compile providers
        run: |
          cargo xtask build all

      - name: Save providers
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: fiberplane-providers
          path: artifacts/*.wasm
