name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3

      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: "https://fiberplanebot:${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/"

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --verbose

      - name: Compile providers
        run: |
          cargo xtask build all --exclude=sample

      - name: Attach providers to release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          fail_on_unmatched_files: true

      - name: Cargo login
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_TOKEN }}

      - name: Publish PDK crates
        run: cargo xtask publish
