name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3

      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: "https://fiberplanebot:${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/"

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --verbose

      - name: Compile providers
        run: |
          cargo xtask build all --exclude=sample

      - name: Attach providers to release
        uses: meeDamian/github-release@2.0
        with:
          allow_override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            artifacts/cloudwatch.wasm
            artifacts/elasticsearch.wasm
            artifacts/https.wasm
            artifacts/loki.wasm
            artifacts/prometheus.wasm
            artifacts/sentry.wasm

      - name: Cargo login
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_TOKEN }}

      - name: Publish PDK crates
        run: cargo xtask publish
