[package]
name = "prometheus-provider"
version = "0.1.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
form_urlencoded = "1"
fp-provider = { version = "1.0.0-alpha.1", path = "../../fp-provider" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
